"""Add resources

Revision ID: 46e8eb898e7c
Revises: 4fa3dbccc5f7
Create Date: 

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e8eb898e7c'
down_revision = '4fa3dbccc5f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('location_id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Text(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['location_id'], ['locations.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    # ### end Alembic commands ###
