"""add captures and history

Revision ID: 4fa3dbccc5f7
Revises: fae27501c0a6
Create Date: 

"""

from alembic import op
import sqlalchemy as sa

from utils.game_staff.basic_hq import BASIC_HQ_ID, BASIC_HQ_CODE, BASIC_HQ_NAME


# revision identifiers, used by Alembic.
revision = '4fa3dbccc5f7'
down_revision = 'fae27501c0a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alliances = op.create_table('alliances',
                                sa.Column('id', sa.Integer(), nullable=False),
                                sa.Column('code', sa.Text(), nullable=False),
                                sa.Column('name', sa.Text(), nullable=False),
                                sa.Column('owner', sa.Text(), nullable=True),
                                sa.Column('pouches', sa.Integer(),
                                          nullable=False, default=0),
                                sa.Column('points', sa.Float(),
                                          nullable=False, default=0),
                                sa.Column('active', sa.Boolean(),
                                          nullable=False, default=True),
                                sa.PrimaryKeyConstraint('id'),
                                sa.UniqueConstraint('code'),
                                sa.UniqueConstraint('name')
                                )
    op.create_table('locations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.Text(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('type', sa.Text(), nullable=False),
                    sa.Column('seen', sa.Boolean(),
                              nullable=False, default=False),
                    sa.Column('life_time', sa.Integer(),
                              nullable=False, default=0),
                    sa.Column('owned_time', sa.Integer(),
                              nullable=False, default=0),
                    sa.Column('owner', sa.Integer(),
                              nullable=False, default=1),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('alliance_id', sa.Integer(),
                              nullable=True),
                    sa.Column('location_id', sa.Integer(),
                              nullable=True),
                    sa.Column('result', sa.Text(), nullable=False),
                    sa.Column('stock', sa.Integer(), nullable=True),
                    sa.Column('glory', sa.Integer(), nullable=True),
                    sa.Column('owner', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['alliance_id'], ['alliances.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['location_id'], ['locations.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    # ### my own commands ###
    op.bulk_insert(alliances, [
        # "Неизвестные силы" is alliance for locations with unknown owners
        {
            'id': 1,
            'name': 'Неизвестные силы',
            'code': 'undefined'
        },
        # "Запретные силы" is alliance for locations which are protected by Forbidden Sentinels
        {
            'id': 2,
            'name': 'Запретные силы',
            'code': 'forbidden'
        },
        # Basic alliance Fresh Eclipse
        {
            'id': BASIC_HQ_ID,
            'name': BASIC_HQ_NAME,
            'code': BASIC_HQ_CODE
        }
    ])
    # ### end my own commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('locations')
    op.drop_table('alliances')
    # ### end Alembic commands ###
