"""Add chats and users

Revision ID: 98d831bd39e2
Revises: ddad018f79aa
Create Date: 

"""
from alembic import op
import sqlalchemy as sa

from utils.configs.super_chats_info import SUPER_CHATS
from utils.configs.super_user_info import SUPER_USERS
from utils.configs.users_and_guilds import USERS_AND_GUILDS
from utils.configs.users_and_chats import USERS_AND_CHATS


# revision identifiers, used by Alembic.
revision = '98d831bd39e2'
down_revision = 'ddad018f79aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    chats = op.create_table('chats',
                            sa.Column('id', sa.BigInteger(), nullable=False),
                            sa.Column('group', sa.Text(), nullable=False),
                            sa.Column('guild', sa.String(
                                length=3), nullable=True),
                            sa.Column('alliance', sa.Integer(), nullable=True),
                            sa.Column('locations_review_allowed',
                                      sa.Boolean(), default=True),
                            sa.Column('withdrawing_allowed',
                                      sa.Boolean(), default=True),
                            sa.Column('triggers_allowed',
                                      sa.Boolean(), default=True),
                            sa.PrimaryKeyConstraint('id'),
                            sa.ForeignKeyConstraint(
                                ['guild'], ['guilds.tag'],
                                ondelete='CASCADE'),
                            sa.ForeignKeyConstraint(
                                ['alliance'], ['alliances.id'],
                                ondelete='CASCADE')
                            )
    users = op.create_table('users',
                            sa.Column('id', sa.BigInteger(), nullable=False),
                            sa.Column('username', sa.Text(), nullable=True),
                            sa.PrimaryKeyConstraint('id'),
                            sa.UniqueConstraint('username')
                            )
    users_and_guilds = op.create_table('users_and_guilds',
                                       sa.Column(
                                           'user_id', sa.BigInteger(), nullable=False),
                                       sa.Column('guild', sa.String(
                                           3), nullable=False),
                                       sa.PrimaryKeyConstraint(
                                           'user_id', 'guild'),
                                       sa.ForeignKeyConstraint(
                                           ['user_id'], ['users.id'],
                                           ondelete='CASCADE'),
                                       sa.ForeignKeyConstraint(['guild'], ['guilds.tag'],
                                                               ondelete='CASCADE'))
    users_and_chats = op.create_table('users_and_chats',
                                      sa.Column(
                                          'user_id', sa.BigInteger(), nullable=False),
                                      sa.Column(
                                          'chat_id', sa.BigInteger(), nullable=False),
                                      sa.Column(
                                          'is_admin', sa.Boolean(), default=False),
                                      sa.PrimaryKeyConstraint(
                                          'user_id', 'chat_id'),
                                      sa.ForeignKeyConstraint(
                                          ['user_id'], ['users.id'],
                                          ondelete='CASCADE'),
                                      sa.ForeignKeyConstraint(
                                          ['chat_id'], ['chats.id'],
                                          ondelete='CASCADE'),
                                      )
    # ### end Alembic commands ###
    # ### own commands
    # SUPER_CHATS structure:
    # {
    #   'id': chat_id,
    #   'group': group_name
    # }
    op.bulk_insert(chats, SUPER_CHATS)
    # SUPER_USERS structure:
    # {
    #   'id': user_id,
    #   'username': username
    # }
    op.bulk_insert(users, SUPER_USERS)
    # USERS_GUILDS structure:
    # {
    #   'user_id': user_id,
    #   'guild': guild_tag
    # }
    op.bulk_insert(users_and_guilds, USERS_AND_GUILDS)
    # USERS_AND_CHATS structure:
    # {
    #   'user_id': user_id,
    #   'chat_id': chat_id
    # }
    op.bulk_insert(users_and_chats, USERS_AND_CHATS)
    # ### end own commands


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_and_chats')
    op.drop_table('users_and_guilds')
    op.drop_table('users')
    op.drop_table('chats')
    # ### end Alembic commands ###
