"""Add triggers

Revision ID: d310e35b41d9
Revises: 94fd025cf39e
Create Date: 

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd310e35b41d9'
down_revision = '94fd025cf39e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triggers',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('type', sa.Text(), nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('message_id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('text_value', sa.Text(), nullable=True),
                    sa.Column('file_id', sa.Text(), nullable=True),
                    sa.Column('strict', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['chat_id'], ['chats.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triggers')
    # ### end Alembic commands ###
