"""Add guilds

Revision ID: ddad018f79aa
Revises: 46e8eb898e7c
Create Date: 

"""
from alembic import op
import sqlalchemy as sa

from utils.game_staff.basic_hq import BASIC_HQ_ID


# revision identifiers, used by Alembic.
revision = 'ddad018f79aa'
down_revision = '46e8eb898e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    guilds = op.create_table('guilds',
                             sa.Column('tag', sa.String(
                                 length=3), nullable=False),
                             sa.Column('name', sa.Text(), nullable=False),
                             sa.Column('castle', sa.Text(), nullable=True),
                             sa.Column('emoji', sa.Text(), nullable=True),
                             sa.Column('level', sa.Integer(), default=0),
                             sa.Column('glory', sa.Integer(), default=0),
                             sa.Column('total_attack',
                                       sa.Integer(), default=0),
                             sa.Column('total_def', sa.Integer(), default=0),
                             sa.Column('active_players_2040',
                                       sa.Integer(), default=0),
                             sa.Column('active_players_4060',
                                       sa.Integer(), default=0),
                             sa.Column('active_players_60+',
                                       sa.Integer(), default=0),
                             sa.Column('total_players_2040',
                                       sa.Integer(), default=0),
                             sa.Column('total_players_4060',
                                       sa.Integer(), default=0),
                             sa.Column('total_players_60+',
                                       sa.Integer(), default=0),
                             sa.Column('alliance', sa.Integer(),
                                       nullable=True),
                             sa.ForeignKeyConstraint(
                                 ['alliance'], ['alliances.id'], ondelete='SET NULL'),
                             sa.PrimaryKeyConstraint('tag')
                             )
    # ### end Alembic commands ###

    # ### own commands
    op.bulk_insert(guilds, [
        {
            'tag': 'TND',
            'name': 'Suicide Squad',
            'castle': "eggplant",
            'alliance': BASIC_HQ_ID
        }
    ])
    # ### end own commands


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guilds')
    # ### end Alembic commands ###
